#https://github.com/sumitmalik5/cicdgke.git

steps:  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/{_CINAME}:{_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/{_CINAME}:{_VERSION}']

substitutions:
   _PROJECT_ID : gcp-devops-464200
   _CINAME : gke-image
   _VERSION : v1.0

options:
  logging : CLOUD_LOGGING_ONLY





  
