#https://github.com/sumitmalik5/cicdgke.git

steps:  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - 'set'
  - 'image'
  - 'deployment/cicd-app-1'
  - 'runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'
  

substitutions:
   _PROJECT_ID : gcp-devops-464200
   _CINAME : gke-image
   _VERSION : v6.0

options:
  logging : CLOUD_LOGGING_ONLY





  
